wordpress:
  enabled: true

  registrySecret: []

  image: wordpress:4.8-apache

  service:
    port: 80
    targetPort: 80
    type: LoadBalancer

  storageClass: 
    name: nfs-client
    size: 10Gi

mysql:
  enabled: true

  registrySecret: []

  image: mysql:5.6

  passwordDatabase: akundb123

  storageClass: 
    name: nfs-client
    size: 10Gi