{{- if .Values.wordpress.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-wordpress-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    tier: {{ .Release.Name }}-wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.wordpress.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.wordpress.storageClass.size }}
{{- end }}