{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Relase.Namespace }}
  labels: 
    app: {{ .Release.Name }}
    tier: {{ .Release.Name }}-mysql
type: Opaque
data:
  password-mysql: {{ .Values.mysql.passwordDatabase | b64enc | quote }}
{{- end }}