{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Release.Name }}
    tier: {{ .Release.Name }}-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: {{ .Release.Name }}
    tier: {{ .Release.Name }}-mysql
  clusterIP: None
{{- end }}